- hosts: centos

  tasks:

    - name: Run ls to test connection and ability
      shell: ls -latr /tmp 
      register: lsout

    - debug: msg="{{ lsout.stdout }}"

    - debug: msg="{{ lsout.stderr }}"

    handlers:
      - name: restart named.service
        service: name=named.service state=restarted
