- hosts: centos

  tasks:

    - name: Run ls to test connection and ability
      shell: sudo cat /var/named/chroot/etc/named.forwards 
      register: lsout

    - debug: msg="{{ lsout.stdout }}"

    - debug: msg="{{ lsout.stderr }}"
