- hosts: centos

  tasks:

    - name: Run ls to test connection and ability
      shell: ls -latr /tmp 
      register: lsout

    - debug: msg="{{ lsout.stdout }}"

    - debug: msg="{{ lsout.stderr }}"
